version: '3.8'

networks:
  nest-net:
    driver: bridge
    name: nest-net

services:
  #postgres
  postgresql:
    image: 'bitnami/postgresql:11'
    ports:
      - '15432:5432'
    environment:
      - POSTGRESQL_DATABASE=${DB_NAME}
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - nest-net
