export const USER_REPOSITORY = 'USER_REPOSITORY';
export const USER_DETAIL_REPOSITORY = 'USER_DETAIL_REPOSITORY';
export const ROLE_REPOSITORY = 'ROLE_REPOSITORY';
export const USER_LEARNING_JOURNEY_REPOSITORY =
  'USER_LEARNING_JOURNEY_REPOSITORY';
export const USER_LEARNING_SUBJECTS_REPOSITORY =
  'USER_LEARNING_SUBJECTS_REPOSITORY';
export const CURRICULUM_LEVELS_REPOSITORY = 'CURRICULUM_LEVELS_REPOSITORY';
export const SUBJECT_REPOSITORY = 'SUBJECT_REPOSITORY';
export const EXAM_REPOSITORY = 'EXAM_REPOSITORY';
export const CHAPTER_REPOSITORY = 'CHAPTER_REPOSITORY';
export const TOPIC_REPOSITORY = 'TOPIC_REPOSITORY';
export const QUIZ_REPOSITORY = 'QUIZ_REPOSITORY';
export const QUIZ_ANSWER_OPTION_REPOSITORY = 'QUIZ_ANSWER_OPTION_REPOSITORY';
export const USER_QUIZ_REPOSITORY = 'USER_QUIZ_REPOSITORY';
export const USER_QUIZ_ANSWER_REPOSITORY = 'USER_QUIZ_ANSWER_REPOSITORY';
export const USER_EXAM_REPOSITORY = 'USER_EXAM_REPOSITORY';
export const USER_EXAM_ANSWER_REPOSITORY = 'USER_EXAM_ANSWER_REPOSITORY';
export const EXAM_ANSWER_OPTION_REPOSITORY = 'EXAM_ANSWER_OPTION_REPOSITORY';
