export const USER_REPOSITORY = 'USER_REPOSITORY';
export const USER_DETAIL_REPOSITORY = 'USER_DETAIL_REPOSITORY';
export const ROLE_REPOSITORY = 'ROLE_REPOSITORY';
export const USER_LEARNING_JOURNEY_REPOSITORY =
  'USER_LEARNING_JOURNEY_REPOSITORY';
export const USER_LEARNING_SUBJECTS_REPOSITORY =
  'USER_LEARNING_SUBJECTS_REPOSITORY';
export const CURRICULUM_LEVELS_REPOSITORY = 'CURRICULUM_LEVELS_REPOSITORY';
export const SUBJECT_REPOSITORY = 'SUBJECT_REPOSITORY';
export const ASSESMENT_REPOSITORY = 'ASSESMENT_REPOSITORY';
export const CHAPTER_REPOSITORY = 'CHAPTER_REPOSITORY';
export const TOPIC_REPOSITORY = 'TOPIC_REPOSITORY';
export const ASSESMENT_QUESTION_REPOSITORY = 'ASSESMENT_QUESTION_REPOSITORY';
export const USER_ASSESMENT_REPOSITORY = 'USER_ASSESMENT_REPOSITORY';
export const USER_ASSESMENT_ANSWER_REPOSITORY = 'USER_ASSESMENT_ANSWER_REPOSITORY';
export const BANK_QUESTION_REPOSITORY = 'BANK_QUESTION_REPOSITORY';
export const ANSWER_OPTION_REPOSITORY = 'ANSWER_OPTION_REPOSITORY';
